# This file was generated by GoReleaser. DO NOT EDIT.
class Checksum < Formula
  desc "SHA256 file verification for consistency check purposes"
  homepage "https://github.com/teran/checksum"
  version "0.8.5-2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/teran/checksum/releases/download/v0.8.5-2/checksum_0.8.5-2_macOS_amd64.tar.gz"
    sha256 "38efdf834c3907977611641db3c618fe365654872c896f4c79e597bcd5438d68"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/teran/checksum/releases/download/v0.8.5-2/checksum_0.8.5-2_linux_amd64.tar.gz"
      sha256 "ea133ae2049875db7ef2bffb318c2f46d4008d5a94282985b4ad714b83ecbae8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/teran/checksum/releases/download/v0.8.5-2/checksum_0.8.5-2_linux_arm64.tar.gz"
        sha256 "15b49589d275d9480e7081f812334e7d19be27023edf29d59644457f9e839413"
      else
        url "https://github.com/teran/checksum/releases/download/v0.8.5-2/checksum_0.8.5-2_linux_armv6.tar.gz"
        sha256 "b08a3c02a45b1ab67c218609b2102c367c0533840d1417eee9683f4c2e8980a5"
      end
    end
  end

  def install
    bin.install "checksum"
  end

  test do
    system "#{bin}/checksum --version"
  end
end
