# This file was generated by GoReleaser. DO NOT EDIT.
class Checksum < Formula
  desc "SHA256 file verification for consistency check purposes"
  homepage "https://github.com/teran/checksum"
  version "0.8.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/teran/checksum/releases/download/v0.8.5/checksum_0.8.5_macOS_amd64.tar.gz"
    sha256 "c7fd2a128992562540128760f829895f0f7d539fb4f9a20780b6f7e18960bcb7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/teran/checksum/releases/download/v0.8.5/checksum_0.8.5_linux_amd64.tar.gz"
      sha256 "1f889813d91f24b39651d310e8b71b56331167ca50a3fd2e805a8937ebebee7e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/teran/checksum/releases/download/v0.8.5/checksum_0.8.5_linux_arm64.tar.gz"
        sha256 "038d2acf745bc8114f6ce74845b742a3d35e7cdf6a3f6ec0e5800370ed19eae4"
      else
        url "https://github.com/teran/checksum/releases/download/v0.8.5/checksum_0.8.5_linux_armv6.tar.gz"
        sha256 "dfc6438a528cea4f5b9639216c5e3c9c8d4a75104b75ef42371bf0b02e366d50"
      end
    end
  end

  def install
    bin.install "checksum"
  end

  test do
    system "#{bin}/checksum -version"
  end
end
