# This file was generated by GoReleaser. DO NOT EDIT.
class Eos1vTagger < Formula
  desc "Canon ES-E1 CSV parsing tool to generate EXIF data for film scans"
  homepage "https://github.com/teran/eos-1v-tagger"
  version "0.1-alpha.16"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/teran/eos-1v-tagger/releases/download/v0.1-alpha.16/eos-1v-tagger_0.1-alpha.16_macOS_amd64.tar.gz"
    sha256 "0c89699d4e6c158d094d202349675c927a743290e77495d83f34b744ac706b02"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/teran/eos-1v-tagger/releases/download/v0.1-alpha.16/eos-1v-tagger_0.1-alpha.16_linux_amd64.tar.gz"
      sha256 "534858c7b080eb8b6dd47c941a7fd3edb2e9cee64bcfa193e9062cb70e840f53"
    end
  end

  def install
    bin.install "eos-1v-tagger"
  end

  test do
    system "#{bin}/eos-1v-tagger -version"
  end
end
