# This file was generated by GoReleaser. DO NOT EDIT.
class Imgsum < Formula
  desc "SHA256 file verification for consistency check purposes"
  homepage "https://github.com/teran/imgsum"
  version "1.1-alpha.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/teran/imgsum/releases/download/1.1-alpha.8/imgsum_1.1-alpha.8_macOS_amd64.tar.gz"
    sha256 "b7fd0fd4e4ee7e9d88b398eb28ece3a4a382a0d182b00a8fcae14fc308b2a67d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/teran/imgsum/releases/download/1.1-alpha.8/imgsum_1.1-alpha.8_linux_amd64.tar.gz"
      sha256 "473b0d3a09339e8cde744f827c763c05db04722c0555f6b381502ea6c5462c5a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/teran/imgsum/releases/download/1.1-alpha.8/imgsum_1.1-alpha.8_linux_arm64.tar.gz"
        sha256 "23c908fb815ff865b2065b76e243de46b96caaef78cd7434b1434449c711bae4"
      else
        url "https://github.com/teran/imgsum/releases/download/1.1-alpha.8/imgsum_1.1-alpha.8_linux_armv6.tar.gz"
        sha256 "b7e0a13ef3214e4bcfed868f35115a5cd131ee662d943a200e7e17a211cb96c2"
      end
    end
  end

  def install
    bin.install "imgsum"
  end

  test do
    system "#{bin}/imgsum -version"
  end
end
